import { Pokemon } from './Pokemon';

export const POKEMON: Pokemon[] = [
    {
      id: 1,
      name: 'Bulbasaur',
      typeOne: 'Grass',
      typeTwo: 'Poison',
      abilities: 'Overgrow;Chlorophyll',
      category: 'Seed Pokémon',
      heightInFeet: 2.04,
      heightInMeters: 1.0,
      weightInPounds: 15,
      weightInKilograms: 7,
      captureRate: 45,
      total: 318,
      healthPoints: 45,
      attack: 49,
      defense: 49,
      specialAttack: 65,
      specialDefense: 65,
      speed: 45
  },
  {
      id: 2,
      name: 'Ivysaur',
      typeOne: 'Grass',
      typeTwo: 'Poison',
      abilities: 'Overgrow;Chlorophyll',
      category: 'Seed Pokémon',
      heightInFeet: 3.03,
      heightInMeters: 1.0,
      weightInPounds: 29,
      weightInKilograms: 13,
      captureRate: 45,
      total: 405,
      healthPoints: 60,
      attack: 62,
      defense: 63,
      specialAttack: 80,
      specialDefense: 80,
      speed: 60
  },
  {
      id: 3,
      name: 'Venusaur',
      typeOne: 'Grass',
      typeTwo: 'Poison',
      abilities: 'Overgrow;Chlorophyll',
      category: 'Seed Pokémon',
      heightInFeet: 6.07,
      heightInMeters: 2.0,
      weightInPounds: 221,
      weightInKilograms: 100,
      captureRate: 45,
      total: 525,
      healthPoints: 80,
      attack: 82,
      defense: 83,
      specialAttack: 100,
      specialDefense: 100,
      speed: 80
  },
  {
      id: 4,
      name: 'Charmander',
      typeOne: 'Fire',
      typeTwo: 'None',
      abilities: 'Blaze;Solar Power',
      category: 'Lizard Pokémon',
      heightInFeet: 2.0,
      heightInMeters: 1.0,
      weightInPounds: 19,
      weightInKilograms: 9,
      captureRate: 45,
      total: 309,
      healthPoints: 39,
      attack: 52,
      defense: 43,
      specialAttack: 60,
      specialDefense: 50,
      speed: 65
  },
  {
      id: 5,
      name: 'Charmeleon',
      typeOne: 'Fire',
      typeTwo: 'None',
      abilities: 'Blaze;Solar Power',
      category: 'Flame Pokémon',
      heightInFeet: 3.07,
      heightInMeters: 1.0,
      weightInPounds: 42,
      weightInKilograms: 19,
      captureRate: 45,
      total: 405,
      healthPoints: 58,
      attack: 64,
      defense: 58,
      specialAttack: 80,
      specialDefense: 65,
      speed: 80
  },
  {
      id: 6,
      name: 'Charizard',
      typeOne: 'Fire',
      typeTwo: 'Flying',
      abilities: 'Blaze;Solar Power',
      category: 'Flame Pokémon',
      heightInFeet: 5.07,
      heightInMeters: 2.0,
      weightInPounds: 200,
      weightInKilograms: 91,
      captureRate: 45,
      total: 534,
      healthPoints: 78,
      attack: 84,
      defense: 78,
      specialAttack: 109,
      specialDefense: 85,
      speed: 100
  }
]
